apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: build-pipeline-run-db-
spec:
  serviceAccountName: build-bot
  params:
    - name: source-repo
      value: https://github.com/cloud-native-garage-method-cohort/emea8-squad4-meme-generator-db
    - name: image-repo
      value: quay.io/levandrejev/squad4-meme-generator-db
    - name: app-name
      value: squad4-meme-generator-db
  pipelineRef:
    name: build-pipeline
  workspaces:
    - name: pipeline-shared-data
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 1Gi
          accessModes:
            - ReadWriteOnce
    - name: gitops-repository
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 1Gi
          accessModes:
            - ReadWriteOnce
    - name: git-credentials
      secret:
        secretName: git-credentials